### PR TITLE
Added multi cursor modifier info message

### PR DESCRIPTION
**Pull request by padamczewski**
Since in latest Visual Studio Code [update](https://code.visualstudio.com/updates/v1_13#_add-multiple-cursors-with-ctrl-cmd-click) new setting for multi cursor modifier was introduced it's now possible to use `ctrl` or `cmd` just like in Sublime Text. However the default option is still `alt` key, which isn't so natural for someone switching from ST to VSCode.

My idea is to show user a message with possibility of changing the VSCode default.
multi-cursor-modifier
The message is shown when user hasn't specified `ctrlCmd` in the settings and until the question has been answered.

The code is just demonstration of functionality, not finished solution.

### CODE REVIEW

**Comment by egamma** [comment]
// fyi @seanmcbreen we have discussed something along these lines in the past.

**Comment by waderyan** [comment]
@padamczewski thank you for your PR. I will take a look at this soon. 

> The code is just demonstration of functionality, not finished solution.

Can you explain more what you mean by this? Do you intend not to have this code brought in to the extension?

**Comment by padamczewski** [comment]
@waderyan: When I was writing the code I was mostly focusing on just handling the case of multi cursor modifier. I didn't take into account whole `Sublime Text Emulation` enhancement, which I've seen only after creating my PR. I used ES6 instead of TypeScript and didn't structure code in the best possible manner because I didn't want to spend much more time making it look better before getting feedback. Main main goal was to present to you how this case could be handled, but if it's meeting your standards, then I'm more than happy to get it merged.

**Comment by waderyan** [comment]
@padamczewski makes sense. The general idea looks good. I'll take a deeper look.

**Comment by waderyan** [comment]
Code looks good. I brought it in. I'll make some changes before publishing, but overall really like what you've done. Keep the PRs coming!

**Pull request merged**
